export default {
	title: 'TypeScript с Vue.js 3',
	chapters: [
		{
			title: 'Глава 1',
			slug: '1-chapter-1',
			number: 1,
			lessons: [
				{
					title: 'Введение в TypeScript с Vue.js 3',
					slug: '1-introduction-to-typescript-with-vue-js-3',
					number: 1,
					downloadUrl: 'https://vueschool.io/lessons/introduction-to-typescript-with-vue-js-3',
					videoId: 684236333,
					text: `В этом уроке мы рассмотрим некоторые преимущества использования TypeScript с Vue.js, в том числе: Улучшенное обнаружение ошибок в вашей среде IDE и во время сборки Более безопасный и менее напряженный рефакторинг Более целенаправленное и точное автозаполнение IDE Мы также отвечаем на вопрос: « Есть ли случаи, когда вы не хотели бы использовать TypeScript?».`,
				},
				{
					title: 'TypeScript в компонентах Vue',
					slug: '2-typescript-in-vue-components',
					number: 2,
					downloadUrl: 'https://vueschool.io/lessons/typescript-in-vue-components',
					videoId: 684012498,
					text: `В этом уроке мы узнаем, как направить компоненты одного файла Vue для работы с TypeScript.`,
				},
				{
					title: 'Ввод событий компонента',
					slug: '3-typing-component-events',
					number: 3,
					downloadUrl: 'https://vueschool.io/lessons/typing-component-events',
					sourceUrl: 'https://vueschool.io/lessons/typing-component-events',
					videoId: 686921522,
					text: `В этом уроке мы узнаем, как вводить полезную нагрузку событий компонента в Vue и TypeScript.`,
				},
			],
		},
		{
			title: 'Глава 2',
			slug: '2-chapter-2',
			number: 2,
			lessons: [
				{
					title: 'Использование TypeScript с API параметров в компонентах',
					slug: '1-using-typescript-with-the-options-api-in-components',
					number: 1,
					downloadUrl: 'https://vueschool.io/lessons/using-typescript-with-the-options-api-in-components',
					sourceUrl: 'https://vueschool.io/lessons/using-typescript-with-the-options-api-in-components',
					videoId: 688503389,
					text: `В этом уроке мы узнаем, как использовать TypeScript с API параметров Vue.js для ввода таких вещей, как реквизиты компонентов, вычисляемые реквизиты и события.`,
				},
				{
					title: 'Объявление и ввод реквизитов компонентов',
					slug: '2-declaring-and-typing-component-props',
					number: 2,
					downloadUrl: 'https://vueschool.io/lessons/declaring-and-typing-component-props',
					sourceUrl: 'https://vueschool.io/lessons/declaring-and-typing-component-props',
					videoId: 688500728,
					text: `В этом уроке мы рассмотрим, как использовать TypeScript для определения типов реквизитов компонента Vue. Попутно вы также увидите из первых рук отличный DX, который обеспечивает взаимодействие с этими компонентами.`,
				},
				{
					title: 'TypeScript в компонентах Vue',
					slug: '3-typescript-in-vue-components',
					number: 3,
					downloadUrl: 'https://vueschool.io/lessons/typescript-in-vue-components',
					videoId: 684012498,
					text: `В этом уроке мы узнаем, как направить компоненты Vue Single File для работы с Typescript.`,
				},
				{
					title: 'Ввод событий компонента',
					slug: '4-typing-component-events',
					number: 4,
					downloadUrl: 'https://vueschool.io/lessons/typing-component-events',
					sourceUrl: 'https://vueschool.io/lessons/typing-component-events',
					videoId: 686921522,
					text: `В этом уроке мы узнаем, как вводить полезную нагрузку событий компонента в Vue и TypeScript.`,
				},
			],
		},
		{
			title: 'Глава 3',
			slug: '3-chapter-3',
			number: 3,
			lessons: [
				{
					title: 'Использование TypeScript с API параметров в компонентах',
					slug: '1-using-typescript-with-the-options-api-in-components',
					number: 1,
					downloadUrl: 'https://vueschool.io/lessons/using-typescript-with-the-options-api-in-components',
					sourceUrl: 'https://vueschool.io/lessons/using-typescript-with-the-options-api-in-components',
					videoId: 688503389,
					text: `В этом уроке мы узнаем, как использовать TypeScript с API параметров Vue.js для ввода таких вещей, как реквизиты компонентов, вычисляемые реквизиты и события.`,
				},
				{
					title: 'Объявление и ввод реквизитов компонентов',
					slug: '2-declaring-and-typing-component-props',
					number: 2,
					downloadUrl: 'https://vueschool.io/lessons/declaring-and-typing-component-props',
					sourceUrl: 'https://vueschool.io/lessons/declaring-and-typing-component-props',
					videoId: 688500728,
					text: `В этом уроке мы рассмотрим, как использовать TypeScript для определения типов реквизитов компонента Vue. Попутно вы также увидите из первых рук отличный DX, который обеспечивает взаимодействие с этими компонентами.`,
				},
				{
					title: 'TypeScript в компонентах Vue',
					slug: '3-typescript-in-vue-components',
					number: 3,
					downloadUrl: 'https://vueschool.io/lessons/typescript-in-vue-components',
					videoId: 684012498,
					text: `В этом уроке мы узнаем, как направить компоненты Vue Single File для работы с Typescript.`,
				},
				{
					title: 'Ввод событий компонента',
					slug: '4-typing-component-events',
					number: 4,
					downloadUrl: 'https://vueschool.io/lessons/typing-component-events',
					sourceUrl: 'https://vueschool.io/lessons/typing-component-events',
					videoId: 686921522,
					text: `В этом уроке мы узнаем, как вводить полезную нагрузку событий компонента в Vue и TypeScript.`,
				},
			],
		},
	],
};